### PR TITLE
Load postgis-vt-util functions

### PR DESCRIPTION
**Pull request by ghost**
For https://github.com/openmaptiles/openmaptiles/pull/214 and https://github.com/openmaptiles/openmaptiles-tools/pull/17

### CODE REVIEW

**Comment by ghost** [comment]
@klokan @jirik Can either of you add the other tag to Docker Hub for the postgis builds? It's now v2.4.

**Comment by klokan** [comment]
Autobuild on the tag names is set now.
I have re-released to trigger the automated build.

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
I redid the tag for 2.4 instead of "v2.4" because for some reason the build sent to Docker Hub was tagged as "v2.4" (https://hub.docker.com/r/openmaptiles/postgis/builds/)

**Pull request merged**
